/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv"
      image_width: 640
      image_height: 480
      camera_name: "ms_lifecam"
      camera_info_url: "file:///home/ubuntu/ros2_ws/src/camera_config/ms_lifecam/config.yaml"
